### ISSUE TITLE
OSX checklist

### ISSUE THREAD

**Issue by danslo** [facebook/hhvm#3417]
Just an issue for me to keep track of what we need to fix the OSX build again:
- [x] Land the weak symbol diff (https://reviews.facebook.net/D21327)
- [x] Land this folly PR (https://github.com/facebook/folly/pull/79)
- [x] Land this folly PR (https://github.com/facebook/folly/pull/80)
- [x] Fix s6_addr16 usage in folly/detail/IPAddress.h (@sgolemon landing this)
- [x] Land @jwatzman internally folly diff that ifdefs the version checks on OSX.
- [x] Make sure all of it makes its way back to github.
- [x] Update hhvm-third-party's folly submodule.
- [x] Update hhvm's third-party submodule.
- [x] Land this HHVM PR (https://reviews.facebook.net/D21501)
- [x] Land this HHVM PR, gcc-static linking (https://reviews.facebook.net/D21933)

That's enough to make it build on OSX for me. 
Tagging some people @ptarjan @jwatzman @denji @mcuadros
