### ISSUE TITLE
3.11.1 Cherry-pick list

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6685]
- [x] fix path handling/fastcgi crashes/404s/500s (#6678)
 - [x] fix hh_client crashes (#6671)
 - [x] `hh_server --check` when already running (#6646)

cc @jwatzman @sgolemon @JoelMarcey

**Comment by fredemmott** [comment]
Believe the 404 issues are fixed, waiting for confirmation in #6648

**Comment by fredemmott** [comment]
last one in: #6774

**Comment by Orvid** [comment]
This already went out.
