### ISSUE TITLE
3.27.1 Cherry Picks

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#8252]
No due date yet.

The priority is for code that works on HHVM 3.27.0 to continue to work in 3.27.1; changes are unlikely to be accepted unless small, self-contained, and straightforward to reason about.

- [x] #8223 : support `"$$foo"` in PHP (17db421a7c39c2a3d6beb22f6715afeb60bcbd21)
- [x] Fix unusual behavior with bracket insertion/matching when using as-you-type formatting (50c593d591302bf1490c974dcbe0e02e6a4fc5f3)
- [x] #8249  Fix parser with *many* `if (Shape::keyExists(...` expressions (042cc8bded4ba22008354f40e25bb4d061b5c662)
- [x] #8240 Hack-only keywords should be allowed as names in PHP files (no fix yet. FB T30807827)
- [x] #8256 Allow subclasses to accept a supertype parameter for implementations of abstract methods (D8868379)
- [x] #8211 Improve `hackfmt` support for docblocks in files using tabs (f46fa3a9f410c714f4ee096b09f48d7a12eb8374)
- [x] #8218 Support vscode debug for xbox request (no fix yet. FB D8730411)
- [x] #8258 ASIO crashes
- [x] #8243 Closures in anonymous classes (f82258044f27dc226ee203412d3d9f8d72bd1cc8)

**Comment by fredemmott** [comment]
Building at the moment. For 3.27.2, https://github.com/facebook/hhvm/issues/8264
